name: Auto Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Auto Tag
        run: |
          chmod +x ./.github/scripts/auto_tag.sh
          ./.github/scripts/auto_tag.sh
