name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: ["Auto Tag on Version Change"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag on main branch
        run: |
          if ! git branch --contains ${{ github.ref_name }} | grep -q "main"; then
            echo "Tag must be on the main branch"
            exit 1
          fi

      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3
          export-templates: true

      - name: Export project to web
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
