name: Deploy to GitHub Pages

on:
  # push:
  #   tags:
  #     - "v*.*.*"
  workflow_run:
    workflows: ["Auto Tag on Version Change"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3
          export-templates: true

      - name: Export project to web
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
